### ISSUE TITLE
Update SF-Mono-Powerline with actual version

### ISSUE THREAD

**Issue by up-to-you** [Twixes/SF-Mono-Powerline#1]
Could you please update fonts with new version, available at https://developer.apple.com/fonts/ ?

**Comment by Twixes** [comment]
I believe this is the latest version, unless there was an update within the last month that I missed?

**Comment by up-to-you** [comment]
Can't look at version right now, but i already checked it today and actual version from apple link is much higher than patched one. 

Maybe they really released it recently.

**EDIT**
actual: 15.0d5e1
patched: 13.1d0e10

**Comment by Twixes** [comment]
It is indeed somehow 2 major versions higher. I can't see any visual difference though, so at the moment this one will stay. Might patch the latest version later.

**Comment by Twixes** [comment]
Just updated to the absolute latest version 16.0d1e1! @up-to-you @joshua-turner #4
