### ISSUE TITLE
Is this okay to redistribute using git?

### ISSUE THREAD

**Issue by jiblime** [Twixes/SF-Mono-Powerline#2]
Hi, I would like to upload an ebuild of this using Gentoo's package manager, Portage, to install this. To accomplish this, Portage uses git to pull the master branch of this repository and then installs the fonts into the system. 

However, I know that you made the notice of this being for personal use only, and I cannot find font licensing on Apple. Would this be okay with you?

**Comment by Twixes** [comment]
That's fine by me, don't know about Apple. Do what you think is right.

**Comment by jiblime** [comment]
Thanks for the input. I'll do some more reading on Apple's licensing and re-open/edit this issue if something comes up about that.
