### ISSUE TITLE
SF-Mono-Powerline Regular becomes too heavy when bolded.

### ISSUE THREAD

**Issue by ppkovachev** [Twixes/SF-Mono-Powerline#3]
This happens only on regular, screenshots below.

[SF-Mono-Powerline](https://i.imgur.com/7TEJfP8.png)

[Regular SF-Mono](https://i.imgur.com/Gx4Ff7A.png)

**Comment by Twixes** [comment]
What app is this? I presume it doesn't detect that this font family has a bold variant and poorly tries to imitate one. Seems more like a bug on the app's side, since Terminal.app, Sketch, Chrome, Firefox all handle this correctly.

**Comment by jiblime** [comment]
That would be [neofetch](https://github.com/dylanaraps/neofetch) ran on KDE's Konsole. I am getting issues with Cmder (cmd alternative for Windows) making all fonts bold/italic, and things that are supposed to be bold/italic are bolder/italicer. Would it be a font naming issue? 

Unable to replicate the issue with Konsole 19.12.0, *Draw intense colors in bold font* is disabled. SF Mono Powerline 10pt, regular.
